FROM python:3
ENV PYTHONUNBUFFERED 1

RUN mkdir /app
WORKDIR /app

ADD ./Pipfile Pipfile
ADD ./Pipfile.lock Pipfile.lock

RUN pip install pipenv

RUN pipenv install --deploy --system

ADD ./webapp/ /app/webapp
WORKDIR /app/webapp

CMD gunicorn --bind=0.0.0.0:$PORT webapp.wsgi

